"""add payment columns to orders

Revision ID: c01dc02dba80
Revises: ab3588ff20ff
Create Date: 2025-12-18 03:53:50.114931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01dc02dba80'
down_revision: Union[str, Sequence[str], None] = 'ab3588ff20ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('menu_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('menu_items', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_proof', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_proof')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.alter_column('menu_items', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('menu_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
