# ORDER STATUS
ORDER_PENDING = "PENDING"
ORDER_PAYMENT_UPLOADED = "PAYMENT_UPLOADED"
ORDER_CONFIRMED = "CONFIRMED"
ORDER_CANCELLED = "CANCELLED"

# PAYMENT STATUS
PAYMENT_UNPAID = "UNPAID"
PAYMENT_WAITING_VERIFICATION = "WAITING_VERIFICATION"
PAYMENT_PAID = "PAID"
PAYMENT_REJECTED = "REJECTED"
